---
title: "Untitled"
author: "LIGUO BAO 30850894"
date: "19/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(naniar)
library(Hmisc)
library(broom)
library(dummies)
Bankruptcy <- readRDS('Bankruptcy.RDS')
```

Exclude non-needed attributes
```{r}
Bankruptcy <- Bankruptcy %>% select(-EmplUnion,-FirmEnd)
```


```{r}
# add an index to the dataset
Bankruptcy <- Bankruptcy %>% mutate(ID = row_number())
# make a quarter
Bankruptcy <- Bankruptcy %>% mutate(Quarter = ceiling(MonthFiled / 3))
```

```{r}
# Categorise sector
agri <- tibble(Industry = unique(Bankruptcy$SICMajGroup) )%>%
  filter(row_number()==53) 
financial <- tibble(Industry = unique(Bankruptcy$SICMajGroup) )%>%
  filter(row_number() %in% c(50,17,30)) 
property <- tibble(Industry = unique(Bankruptcy$SICMajGroup) )%>%
  filter(row_number() %in% c(27,33,34,37,29,42)) 
service <- tibble(Industry = unique(Bankruptcy$SICMajGroup) )%>%
  filter(row_number() %in% c(22,28,47,51,8,24,54,55,11,38,20,52))

industrial <- tibble(Industry = unique(Bankruptcy$SICMajGroup) )%>%
  filter(row_number() %in% c(4,6,9,1,21,39,41,13,2,35,19,3,45,14))

consumption <- tibble(Industry = unique(Bankruptcy$SICMajGroup) )%>%
  filter(row_number() %in% c(43,44,40,32,23,31,15,46,25,18,16,5,7,36,12))

resource <- tibble(Industry = unique(Bankruptcy$SICMajGroup) )%>%
  filter(row_number() %in% c(10,26,48,49))

b <- data.frame()
assign_sector <- function(industry,sector){
  for(i in 1:length(industry)){
  a <- Bankruptcy %>% filter(SICMajGroup %in% industry$Industry)  %>% mutate(Sector = sector)
  b <-   rbind(a,b)
  }
  return(b)
}

df1 <- assign_sector(financial,"Financial")
df2 <- assign_sector(property, "Property")
df3 <- assign_sector(service, "Service")
df4 <- assign_sector(industrial, "Industrial")
df5 <- assign_sector(consumption, "Consumption")
df6 <- assign_sector(agri,"Agriculture")
df7 <- assign_sector(resource,"Resource")

Bankruptcy <-  rbind(df1,df2,df3,df4,df5,df6, df7)
```
Categorise variables
```{r factor}
Bankruptcy$CityFiled <- as.factor(Bankruptcy$CityFiled)
Bankruptcy$HeadStAtFiling <- as.factor(Bankruptcy$HeadStAtFiling)
Bankruptcy$SICMajGroup <- as.factor(Bankruptcy$SICMajGroup)
Bankruptcy$Sector <- as.factor(Bankruptcy$Sector)
```

```{r}
Bankruptcy%>% 
  filter(ID != 58) %>% 
  column_to_rownames('ID') %>% 
  select_if(is.numeric) %>%
  select(-Quarter) %>% 
  na.omit() %>% 
  filter()-> pca_data
bkc <- Bankruptcy %>% semi_join(pca_data, by = 'Ebit')
bkc_pca<- prcomp(pca_data[1:14], center = TRUE, scale = TRUE) 
join <- bkc %>% mutate(PC1 = bkc_pca$x[,1], PC2 = bkc_pca$x[,2], PC3 = bkc_pca$x[,3])

screeplot(bkc_pca,type = 'l', main = "Scree plot of PCA")

bkc_pca_var <- tibble(PC=1:length(bkc_pca$sdev), prop.var=bkc_pca$sdev^2)
bkc_pcs <- as_tibble(bkc_pca$x[,1:3]) %>%
  mutate(company=bkc$Name)
bkc_pcs_evc <- as_tibble(bkc_pca$rotation[,1:3]) %>% 
  mutate(origin = rep(0,14), variables = colnames(pca_data)) %>% 
  mutate(PC1s = PC1*(bkc_pca_var$prop.var[1]*2),
         PC2s = PC2*(bkc_pca_var$prop.var[2]*2),
         PC3s = PC3*(bkc_pca_var$prop.var[3]*2))
```

```{r}
library(plot3D)
library(plot3Drgl)
par(mar = c(1.2,1.2,1.2,1.2))
scatter3D(bkc_pcs$PC1, bkc_pcs$PC2, bkc_pcs$PC3, 
          pch = 20, theta = 150, phi = 10,
          ticktype = "detailed",
     colvar= as.integer(factor(bkc$DENYOther )),
     col = gg2.col(3),
     colkey = list(
       at = c(
         unique(as.integer(factor(bkc$DENYOther)))),
       side = 4, length = 1, width = 0.5, labels = unique(factor(bkc$DENYOther))),
      xlab = "PC1", ylab = "PC2", zlab = "PC3", main = "PCs agaisnt DENYOther", clab = "DENYOther"
     )
points3D(bkc_pcs_evc$origin, bkc_pcs_evc$origin, bkc_pcs_evc$origin, add = TRUE, col="blue", 
          colkey = FALSE, pch = 19, cex = 1)
arrows3D(bkc_pcs_evc$origin, bkc_pcs_evc$origin, bkc_pcs_evc$origin,
         bkc_pcs_evc$PC1s, bkc_pcs_evc$PC2s, bkc_pcs_evc$PC3s,
         phi = 0, theta = 90,
         lwd = 2, d = 3, clab = c("Quality", "score"), 
         main = "Loading", bty ="g", ticktype = "detailed", overlay = T,add = T)
text3D( bkc_pcs_evc$PC1s, bkc_pcs_evc$PC2s, bkc_pcs_evc$PC3s,  
       c(bkc_pcs_evc$variables),
       add=TRUE, colkey = FALSE, col = "red")
```

```{r}
biplot_sector <- ggplot() + 
  geom_point(data=join, aes(x=PC2, y=PC3, col = Sector)) +
 # geom_text(data=filter(bkc_pcs, abs(PC2)>3.6,), aes(x=PC1, y=PC2, label=company), nudge_y =0.2, nudge_x=-0.1) +
  xlab("PC2") + ylab("PC3") + 
  #xlim(-10,8) + ylim(-5, 10) +
  theme(aspect.ratio=1)  +
  theme_classic() +
  geom_segment(data=bkc_pcs_evc, aes(x=origin, xend=PC2s, y=origin, yend=PC3s), colour="black") +
  ggrepel:: geom_text_repel(data=bkc_pcs_evc, aes(x=PC2s, y=PC3s, label=variables), colour="red", nudge_y=sign(bkc_pcs_evc$PC3)*0.2)+
  labs(x = "PC2", y = "PC3", title = "Biplot", subtitle = "Variables projected onto PC2 and PC3") 
biplot_sector
```
```{r}
biplot_deny <- ggplot() + 
  geom_point(data=join, aes(x=PC2, y=PC3, col = DENYOther)) +
  xlab("PC2") + ylab("PC3") + 
  theme(aspect.ratio=1) +
  theme_classic() +
  geom_segment(data=bkc_pcs_evc, aes(x=origin, xend=PC2s, y=origin, yend=PC3s), colour="black") +
  ggrepel:: geom_text_repel(data=bkc_pcs_evc, aes(x=PC2s, y=PC3s, label=variables), colour="red", nudge_x=0.1, nudge_y=sign(bkc_pcs_evc$PC3)*0.2)+
  labs(x = "PC2", y = "PC3", title = "Biplot", subtitle = "Variables projected onto PC2 and PC3") 
biplot_deny

```

